version: "3"
networks:
  test-network:
    driver: bridge

volumes:
  certs:
    external: true
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  logstash-data:
    driver: local
  logstash-ingest-data:
    driver: local

services:
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - ELASTIC_PASSWORD=featherApril05
      - xpack.license.self_generated.type=basic
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - test-network
    restart: always

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - test-network
    restart: always
