server:
    port: 9100

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedHeaders:
              - '*'
            allow-credentials: true
            allowedMethods:
              - '*'
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    fetch-registry: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions

#info:
#  app:
#    name: gateway
#    description: gateway
#    version: 1.0.0