version: "3"
services:
  mysql:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - test-network
  zipkin:
    depends_on:
      - mysql
    image: openzipkin/zipkin
    container_name: zipkin
    user: root
    ports:
      - 9411:9411
    networks:
      - test-network
    restart: always
    volumes:
      - certs:/zipkin/certs
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin

networks:
  test-network:
    external: true

volumes:
  certs:
    external: true
