server:
    port: 8282

spring:
  application:
    name: demo2
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.example: DEBUG
  file:
    name: '/opt/logs/demo2.log'
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Taipei

cors:
  allowed:
    origin: "http://demo:8080"