version: "3"
networks:
  test-network:
    driver: overlay

volumes:
  logs:
    driver: local

services:
  demo2:
    image: demo2
    ports:
      - 8080:8080
    volumes:
      - logs:/opt/logs
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.30"
          memory: 1G
        reservations:
          cpus: '0.20'
          memory: 100M
      placement:
        constraints:
          - node.role == worker
